CREATE DATABASE IF NOT EXISTS Game;

USE Game;

CREATE TABLE IF NOT EXISTS Account (
id INT(11) NOT_NULL AUTO_INCREMENT,
username VARCHAR(50) NOT_NULL,
lastLoginAttempt INT(11) DEFAULT 0,
password VARCHAR(255),
PRIMARY KEY (Id));