// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/whiuk/philip/mmorpg/server/game/ai/messages.proto

package com.whiuk.philip.mmorpg.server.game.ai;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InformMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code InformMessage}
   */
  public static final class InformMessage extends
      com.google.protobuf.GeneratedMessage
      implements InformMessageOrBuilder {
    // Use InformMessage.newBuilder() to construct.
    private InformMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InformMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InformMessage defaultInstance;
    public static InformMessage getDefaultInstance() {
      return defaultInstance;
    }

    public InformMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InformMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_InformMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_InformMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<InformMessage> PARSER =
        new com.google.protobuf.AbstractParser<InformMessage>() {
      public InformMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InformMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InformMessage> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InformMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_InformMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_InformMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage.Builder.class);
      }

      // Construct using com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_InformMessage_descriptor;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage getDefaultInstanceForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage.getDefaultInstance();
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage build() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage buildPartial() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage result = new com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage) {
          return mergeFrom((com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage other) {
        if (other == com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whiuk.philip.mmorpg.server.game.ai.Messages.InformMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InformMessage)
    }

    static {
      defaultInstance = new InformMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InformMessage)
  }

  public interface RequestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code RequestMessage}
   */
  public static final class RequestMessage extends
      com.google.protobuf.GeneratedMessage
      implements RequestMessageOrBuilder {
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestMessage defaultInstance;
    public static RequestMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RequestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_RequestMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestMessage> PARSER =
        new com.google.protobuf.AbstractParser<RequestMessage>() {
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_RequestMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage.Builder.class);
      }

      // Construct using com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_RequestMessage_descriptor;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage getDefaultInstanceForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage.getDefaultInstance();
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage build() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage buildPartial() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage result = new com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage) {
          return mergeFrom((com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage other) {
        if (other == com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whiuk.philip.mmorpg.server.game.ai.Messages.RequestMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RequestMessage)
    }

    static {
      defaultInstance = new RequestMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RequestMessage)
  }

  public interface OfferMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code OfferMessage}
   */
  public static final class OfferMessage extends
      com.google.protobuf.GeneratedMessage
      implements OfferMessageOrBuilder {
    // Use OfferMessage.newBuilder() to construct.
    private OfferMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OfferMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OfferMessage defaultInstance;
    public static OfferMessage getDefaultInstance() {
      return defaultInstance;
    }

    public OfferMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OfferMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_OfferMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_OfferMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<OfferMessage> PARSER =
        new com.google.protobuf.AbstractParser<OfferMessage>() {
      public OfferMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OfferMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OfferMessage> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OfferMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_OfferMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_OfferMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage.Builder.class);
      }

      // Construct using com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_OfferMessage_descriptor;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage getDefaultInstanceForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage.getDefaultInstance();
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage build() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage buildPartial() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage result = new com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage) {
          return mergeFrom((com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage other) {
        if (other == com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whiuk.philip.mmorpg.server.game.ai.Messages.OfferMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OfferMessage)
    }

    static {
      defaultInstance = new OfferMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OfferMessage)
  }

  public interface PromiseMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code PromiseMessage}
   */
  public static final class PromiseMessage extends
      com.google.protobuf.GeneratedMessage
      implements PromiseMessageOrBuilder {
    // Use PromiseMessage.newBuilder() to construct.
    private PromiseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PromiseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PromiseMessage defaultInstance;
    public static PromiseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public PromiseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PromiseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_PromiseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_PromiseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<PromiseMessage> PARSER =
        new com.google.protobuf.AbstractParser<PromiseMessage>() {
      public PromiseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PromiseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PromiseMessage> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PromiseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_PromiseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_PromiseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage.Builder.class);
      }

      // Construct using com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_PromiseMessage_descriptor;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage getDefaultInstanceForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage.getDefaultInstance();
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage build() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage buildPartial() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage result = new com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage) {
          return mergeFrom((com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage other) {
        if (other == com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whiuk.philip.mmorpg.server.game.ai.Messages.PromiseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PromiseMessage)
    }

    static {
      defaultInstance = new PromiseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PromiseMessage)
  }

  public interface DeclineMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code DeclineMessage}
   */
  public static final class DeclineMessage extends
      com.google.protobuf.GeneratedMessage
      implements DeclineMessageOrBuilder {
    // Use DeclineMessage.newBuilder() to construct.
    private DeclineMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeclineMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeclineMessage defaultInstance;
    public static DeclineMessage getDefaultInstance() {
      return defaultInstance;
    }

    public DeclineMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeclineMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_DeclineMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_DeclineMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<DeclineMessage> PARSER =
        new com.google.protobuf.AbstractParser<DeclineMessage>() {
      public DeclineMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeclineMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeclineMessage> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeclineMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_DeclineMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_DeclineMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage.class, com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage.Builder.class);
      }

      // Construct using com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.internal_static_DeclineMessage_descriptor;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage getDefaultInstanceForType() {
        return com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage.getDefaultInstance();
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage build() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage buildPartial() {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage result = new com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage) {
          return mergeFrom((com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage other) {
        if (other == com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.whiuk.philip.mmorpg.server.game.ai.Messages.DeclineMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DeclineMessage)
    }

    static {
      defaultInstance = new DeclineMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DeclineMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_InformMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InformMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OfferMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OfferMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PromiseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PromiseMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DeclineMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DeclineMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5com/whiuk/philip/mmorpg/server/game/ai" +
      "/messages.proto\"\017\n\rInformMessage\"\020\n\016Requ" +
      "estMessage\"\016\n\014OfferMessage\"\020\n\016PromiseMes" +
      "sage\"\020\n\016DeclineMessageB2\n&com.whiuk.phil" +
      "ip.mmorpg.server.game.aiB\010Messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_InformMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_InformMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_InformMessage_descriptor,
              new java.lang.String[] { });
          internal_static_RequestMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_RequestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RequestMessage_descriptor,
              new java.lang.String[] { });
          internal_static_OfferMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_OfferMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OfferMessage_descriptor,
              new java.lang.String[] { });
          internal_static_PromiseMessage_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_PromiseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PromiseMessage_descriptor,
              new java.lang.String[] { });
          internal_static_DeclineMessage_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_DeclineMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DeclineMessage_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
